### PR TITLE
Hawk-pack stateful searches

### PR DESCRIPTION
**Pull request by rdragos**
This mutability is needed so we can get access to the mutable session that belongs to the new Vector Store implementation in iris-search.

### CODE REVIEW

**Review by iliailia — APPROVED** [review]
Thanks! Could you add a PR description why we need mutability here?

**Comment by rdragos** [comment]
Sure! It's mostly because we need access to a `mut Session` which belongs to the new Vector store implementation in iri-mpc-cpu.

**Comment by iliailia** [comment]
> Sure! It's mostly because we need access to a `mut Session` which belongs to the new Vector store implementation in iri-mpc-cpu.

Should then `eval_distance` and `eval_distance_batch` have a mutable `self` argument?

**Comment by rdragos** [comment]
They should, but I haven't gotten the chance to update my PR with the newest eval_distance :smile:

**Comment by rdragos** [comment]
Let me see what I can do

**Comment by rdragos** [comment]
fortunately I didn't need those to be `mut self` but they will need to be refactored in the future :grin:

**Comment by iliailia** [comment]
> fortunately I didn't need those to be `mut self` but they will need to be refactored in the future 😁

is it because you call them as a subroutine of `less_than` and `is_match`?

**Comment by rdragos** [comment]
yep, I kept the old format since at the time of forking I didn't have the batch distance :smile:

**Pull request merged**
